import { useState } from 'react';
import './DesignLab.css';

type Theme = 'signal' | 'atelier' | 'index';
type DesignLabProps = { onBack?: () => void; onApply?: (theme: Theme) => void };

const concepts = [
  { id: 'signal' as const, number: '01', name: 'Signal', character: 'Энергия совместной работы', description: 'Тёплая бумага, графит и лаймовый акцент. Крупная типографика направляет внимание, а тёмная навигация собирает рабочее пространство.', palette: ['#F4F3EB', '#20251F', '#D4ED62'], fonts: 'Unbounded + Manrope', approach: 'Выразительная обложка · спокойная рабочая зона', reference: 'Awwwards / выразительная композиция' },
  { id: 'atelier' as const, number: '02', name: 'Atelier', character: 'Идеи с человеческим характером', description: 'Редакционная композиция, выразительная антиква и терракотовые детали. Каждая задача выглядит как история, к которой хочется присоединиться.', palette: ['#F6F0E7', '#302B26', '#B9472F'], fonts: 'Georgia + Manrope', approach: 'Журнальная вёрстка · тёплые материалы', reference: 'SiteInspire / редакционная типографика' },
  { id: 'index' as const, number: '03', name: 'Index', character: 'Ясность в каждой детали', description: 'Чёткая сетка, кобальтовый акцент и компактные строки. Задачи, команды и статусы легко сравнить одним взглядом.', palette: ['#F4F6FA', '#182132', '#254CD3'], fonts: 'Manrope + monospace', approach: 'Швейцарская сетка · открытые таблицы', reference: 'Mobbin / ясные продуктовые сценарии' },
];

function Arrow({ diagonal = false }: { diagonal?: boolean }) {
  return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d={diagonal ? 'M6 18 18 6M6 6h12v12' : 'M4 12h16m-6-6 6 6-6 6'} stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" /></svg>;
}

function Emblem() {
  return <svg className="design-lab-emblem" viewBox="0 0 160 160" fill="none" aria-hidden="true"><path d="M80 11v138M11 80h138M31 31l98 98M31 129l98-98" stroke="currentColor" strokeWidth="22" /><circle cx="80" cy="80" r="24" fill="var(--design-paper)" /></svg>;
}

function SignalPreview() {
  return <div className="design-lab-screen design-lab-signal-screen">
    <aside className="design-lab-preview-rail"><strong className="design-lab-preview-brand">sana<span>↗</span></strong><small>РАБОЧЕЕ ПРОСТРАНСТВО</small><span className="design-lab-rail-current">Обзор <span>01</span></span><span>Мои задачи <span>03</span></span><span>Отклики <span>08</span></span><div className="design-lab-rail-note">Идеи<br />становятся<br /><em>делом.</em></div><div className="design-lab-preview-person"><span>АК</span><div>Алия К.<small>Бизнес-пространство</small></div></div></aside>
    <div className="design-lab-signal-content"><div className="design-lab-preview-topline"><span>Пространство / Обзор</span><span>Бизнес <span aria-hidden="true">↗</span></span></div>
      <div className="design-lab-signal-hero"><div><p className="design-lab-overline">ОТ ПЕРВОЙ ИДЕИ ДО РЕЗУЛЬТАТА</p><h2>Большие идеи.<br /><span>Общее дело.</span></h2><p>Ваша следующая задача — чей-то первый<br className="design-lab-desktop-break" /> настоящий проект.</p><span className="design-lab-mock-action">Создать задачу <Arrow /></span></div><div className="design-lab-signal-art"><Emblem /><span>БИЗНЕС + ТАЛАНТЫ</span></div></div>
      <div className="design-lab-signal-stats"><div><strong>03</strong><span>Задачи в работе</span></div><div><strong>08</strong><span>Откликов от команд</span></div><div><strong>02</strong><span>Новых результата</span></div></div>
      <div className="design-lab-preview-section"><h3>Продолжим начатое</h3><span>Все задачи <Arrow /></span></div>
      <div className="design-lab-signal-task"><div><span className="design-lab-preview-tag">E-COMMERCE · ЧАТ-БОТ</span><h3>Помощник для покупателей<br />локального магазина</h3><p>Уточните ожидаемый результат, чтобы командам<br className="design-lab-desktop-break" /> было проще оценить задачу.</p></div><div className="design-lab-preview-score"><strong>76<small>/ 100</small></strong><span>Качество задачи</span><span className="design-lab-preview-gain">+12 за критерии успеха</span></div></div>
    </div>
  </div>;
}

function AtelierPreview() {
  return <div className="design-lab-screen design-lab-atelier-screen">
    <header className="design-lab-atelier-masthead"><strong>sana.</strong><div><span className="design-lab-atelier-current">Мастерская</span><span>Задачи</span><span>Команды</span></div><span className="design-lab-atelier-avatar">АК</span></header>
    <div className="design-lab-atelier-topline"><span>МЕСТО, ГДЕ ИДЕИ ОБРЕТАЮТ ФОРМУ</span><span>Выпуск 01 / Ваша мастерская</span></div>
    <div className="design-lab-atelier-hero"><div><p className="design-lab-overline">БИЗНЕС ВСТРЕЧАЕТ ТАЛАНТЫ</p><h2>Хорошая идея<br />ищет <em>своих.</em></h2><p>Расскажите, что хотите изменить.<br />Найдите команду, которой это близко.</p><span className="design-lab-mock-action">Начать историю <Arrow diagonal /></span></div><div className="design-lab-atelier-art"><span>ОТ ЗАМЫСЛА<br />К РЕЗУЛЬТАТУ</span><svg viewBox="0 0 260 220" fill="none" aria-hidden="true"><path d="M35 185V85a95 95 0 0 1 190 0v100M67 185V91a63 63 0 1 1 126 0v94M100 185V97a30 30 0 0 1 60 0v88" stroke="currentColor" strokeWidth="22" /><path d="M22 202h216" stroke="currentColor" strokeWidth="2" /></svg><small>ДВА ВЗГЛЯДА. ОДНО РЕШЕНИЕ.</small></div></div>
    <div className="design-lab-atelier-bottom"><div className="design-lab-atelier-story"><span className="design-lab-overline">01 / ИЗ ВАШЕЙ МАСТЕРСКОЙ</span><h3>Маленький магазин.<br />Большая забота о клиентах.</h3><p>Помощник, который знает ассортимент и отвечает покупателям вовремя.</p><span className="design-lab-atelier-story-footer">Чат-бот для магазина <Arrow diagonal /></span></div><div className="design-lab-atelier-numbers"><div><strong>3</strong><span>идеи в работе</span></div><div><strong>8</strong><span>команд откликнулись</span></div><p>Следующий шаг —<br /><strong>выбрать команду.</strong></p></div></div>
  </div>;
}

function IndexPreview() {
  const tasks = [{ id: '001', title: 'Помощник для покупателей магазина', kind: 'Чат-бот / E-commerce', score: '76', state: 'Уточнение' }, { id: '002', title: 'Запись клиентов в студию', kind: 'Веб-сервис / Услуги', score: '92', state: 'Подбор команды' }, { id: '003', title: 'Аналитика продаж кофейни', kind: 'Дашборд / Ритейл', score: '85', state: 'В работе' }];
  return <div className="design-lab-screen design-lab-index-screen"><header className="design-lab-index-header"><strong>SANA<span>+</span></strong><div><span className="design-lab-index-active">01 Обзор</span><span>02 Задачи</span><span>03 Команды</span></div><span>АК / БИЗНЕС</span></header><div className="design-lab-index-content"><div className="design-lab-index-intro"><div><p className="design-lab-overline">WORKSPACE — 001</p><h2>Идея.<br />Команда.<br /><span>Результат.</span></h2></div><div className="design-lab-index-summary"><p>Рабочее пространство<br />для задач, которые<br />имеют значение.</p><span className="design-lab-mock-action">Новая задача <Arrow /></span></div></div><div className="design-lab-index-metrics"><div><span>АКТИВНЫЕ ЗАДАЧИ</span><strong>03</strong></div><div><span>ОТКЛИКИ КОМАНД</span><strong>08</strong></div><div><span>ЗАВЕРШЁННЫЕ ЭТАПЫ</span><strong>02</strong></div></div><div className="design-lab-preview-section"><h3>Реестр задач</h3><span>03 записи</span></div><div className="design-lab-index-table" role="table" aria-label="Пример реестра задач"><div className="design-lab-index-row design-lab-index-table-head" role="row"><span role="columnheader">№</span><span role="columnheader">ЗАДАЧА</span><span role="columnheader">РЕЙТИНГ</span><span role="columnheader">СТАТУС</span></div>{tasks.map(task => <div className="design-lab-index-row" role="row" key={task.id}><span role="cell">{task.id}</span><div role="cell"><strong>{task.title}</strong><small>{task.kind}</small></div><strong role="cell">{task.score}<small> /100</small></strong><span role="cell" className="design-lab-index-status">{task.state}</span></div>)}</div></div></div>;
}

export default function DesignLab({ onBack, onApply }: DesignLabProps) {
  const [selected, setSelected] = useState<Theme>('signal');
  const [applied, setApplied] = useState<Theme | null>(null);
  const concept = concepts.find(item => item.id === selected)!;
  function apply() { setApplied(selected); onApply?.(selected); }
  return <main className={`design-lab design-lab-theme-${selected}`}>
    <header className="design-lab-header"><a className="design-lab-wordmark" href="/" onClick={onBack ? event => { event.preventDefault(); onBack(); } : undefined}>sana<span>↗</span></a><span className="design-lab-header-label">DESIGN EXPLORATIONS / 2026</span><button type="button" className="design-lab-back" onClick={() => onBack ? onBack() : window.location.assign('/')}><span>В приложение</span><Arrow /></button></header>
    <div className="design-lab-body"><section className="design-lab-intro"><div><p className="design-lab-overline">ТРИ НАПРАВЛЕНИЯ ДЛЯ AI SANA</p><h1>Характер<br />имеет <span>значение.</span></h1></div><p className="design-lab-intro-copy">Одна платформа, три разных ощущения.<br />Сравните дизайн-системы и выберите,<br className="design-lab-desktop-break" /> в какой хочется работать.</p></section>
      <div className="design-lab-concepts" aria-label="Выбор дизайн-системы">{concepts.map(item => <button type="button" key={item.id} className={`design-lab-concept design-lab-concept-${item.id}${selected === item.id ? ' is-selected' : ''}`} data-theme-choice={item.id} aria-pressed={selected === item.id} onClick={() => setSelected(item.id)} aria-controls="design-lab-preview"><div className="design-lab-concept-top"><span>{item.number}</span><span>{item.id === 'signal' ? 'РЕКОМЕНДУЕМ' : item.id === 'atelier' ? 'РЕДАКЦИОННЫЙ' : 'СИСТЕМНЫЙ'}</span></div><div className="design-lab-concept-name"><strong>{item.name}</strong><Arrow diagonal /></div><p>{item.character}</p><div className="design-lab-mini-layout" aria-hidden="true"><i /><div><b /><span /><span /></div></div><div className="design-lab-concept-colors" aria-hidden="true">{item.palette.map(color => <span key={color} style={{ background: color }} />)}</div></button>)}</div>
      <section id="design-lab-preview" className="design-lab-preview" aria-label={`Предварительный дизайн ${concept.name}`}><div className="design-lab-preview-heading"><div><span className="design-lab-overline">{concept.number} / ПРЕДВАРИТЕЛЬНЫЙ ВАРИАНТ</span><h2>{concept.name}<span>{concept.character}</span></h2></div><button type="button" className="design-lab-apply" data-apply-design onClick={apply} disabled={!onApply}>Применить {concept.name}<Arrow /></button></div><div className="design-lab-preview-frame"><div className="design-lab-windowbar"><span className="design-lab-window-dots" aria-hidden="true"><i /><i /><i /></span><span>AI Sana / Рабочее пространство</span><span>ПРИМЕР ДАННЫХ</span></div>{selected === 'signal' ? <SignalPreview /> : selected === 'atelier' ? <AtelierPreview /> : <IndexPreview />}</div><div className="design-lab-preview-caption"><p>{concept.description}</p><span>Применение меняет цвета и типографику приложения. Композиция выше — предварительный вариант с примерами задач.</span></div></section>
      <section className="design-lab-system" aria-label={`Компоненты системы ${concept.name}`}><div className="design-lab-system-title"><p className="design-lab-overline">СИСТЕМА В ДЕТАЛЯХ</p><h2>Не только<br />красивая обложка.</h2><p>{concept.approach}</p></div><div className="design-lab-system-colors"><h3>01 / Палитра</h3><div className="design-lab-swatches">{concept.palette.map((color, index) => <div key={color}><span style={{ background: color }} /><strong>{['Поверхность', 'Текст', 'Акцент'][index]}</strong><code>{color}</code></div>)}</div></div><div className="design-lab-system-type"><h3>02 / Типографика</h3><div className="design-lab-type-sample">Аа Бб 123</div><p>{concept.fonts}</p><span>Задачи, которые меняют повседневность.</span></div><div className="design-lab-system-components"><h3>03 / Компоненты</h3><span className="design-lab-component-button">Создать задачу <Arrow /></span><div><span className="design-lab-component-status">В работе</span><span className="design-lab-component-score">76 <small>/ 100</small></span></div><p>Единый акцент. Понятные статусы.<br />Чёткая иерархия действий.</p></div></section>
      <section className="design-lab-references"><p className="design-lab-overline">ОТКУДА ПРИЁМЫ</p><div><h2>Вдохновение,<br />переведённое в продукт.</h2><p>Подборка Plerdy — отправная точка. Берём выразительную типографику, ритм сетки и ясные сценарии, затем адаптируем их под задачи AI Sana.</p><nav aria-label="Источники дизайн-вдохновения"><a href="https://www.plerdy.com/ru/blog/top-50-web-design-inspiration-websites/" target="_blank" rel="noreferrer">Plerdy <Arrow diagonal /></a><a href="https://www.awwwards.com/" target="_blank" rel="noreferrer">Awwwards <Arrow diagonal /></a><a href="https://www.siteinspire.com/" target="_blank" rel="noreferrer">SiteInspire <Arrow diagonal /></a><a href="https://land-book.com/" target="_blank" rel="noreferrer">Land-book <Arrow diagonal /></a><a href="https://mobbin.com/" target="_blank" rel="noreferrer">Mobbin <Arrow diagonal /></a></nav></div></section>
      <footer className="design-lab-footer"><span>AI SANA / DESIGN LAB</span><span aria-live="polite">{applied ? `Выбрано направление ${concepts.find(item => item.id === applied)?.name}` : 'Выберите направление — и попробуйте его в приложении.'}</span></footer>
    </div>
  </main>;
}
