-- Optional newsletters: only the backend service key can reach these tables/RPCs.
-- Apply after 202609230001_profiles.sql. Auth confirmation/recovery emails bypass
-- this queue and are sent by Supabase Auth using its own Custom SMTP settings.
begin;

create table if not exists public.mail_campaigns (
    id bigint generated by default as identity primary key,
    subject text not null check (char_length(subject) between 1 and 200),
    created_by uuid references auth.users (id) on delete set null,
    created_at bigint not null default extract(epoch from now())::bigint
);

create table if not exists public.mail_outbox (
    id bigint generated by default as identity primary key,
    campaign_id bigint not null references public.mail_campaigns (id) on delete cascade,
    user_id uuid not null references auth.users (id) on delete cascade,
    recipient text not null,
    subject text not null,
    body text not null,
    status text not null default 'pending'
        check (status in ('pending', 'sending', 'sent', 'preview', 'failed', 'skipped')),
    attempts integer not null default 0 check (attempts >= 0),
    next_attempt bigint not null default 0,
    last_error text,
    created_at bigint not null default extract(epoch from now())::bigint,
    unique (campaign_id, user_id)
);

create index if not exists mail_outbox_due_idx on public.mail_outbox (next_attempt, id)
    where status in ('pending', 'sending');

create table if not exists public.mail_unsubscribe_tokens (
    token_hash text primary key,
    user_id uuid not null references auth.users (id) on delete cascade,
    expires_at bigint not null
);
create index if not exists mail_unsubscribe_user_idx on public.mail_unsubscribe_tokens (user_id);

alter table public.mail_campaigns enable row level security;
alter table public.mail_outbox enable row level security;
alter table public.mail_unsubscribe_tokens enable row level security;
revoke all on public.mail_campaigns, public.mail_outbox, public.mail_unsubscribe_tokens
    from public, anon, authenticated;
revoke all on sequence public.mail_campaigns_id_seq, public.mail_outbox_id_seq
    from public, anon, authenticated;
grant all on public.mail_campaigns, public.mail_outbox, public.mail_unsubscribe_tokens to service_role;
grant usage, select on sequence public.mail_campaigns_id_seq, public.mail_outbox_id_seq to service_role;
-- There are intentionally no anon/authenticated RLS policies for these tables.

create or replace function public.queue_newsletter(
    p_actor uuid, p_subject text, p_text text, p_auth_page_url text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_campaign bigint;
    v_queued integer := 0;
    v_now bigint := extract(epoch from now())::bigint;
    v_token text;
    v_rec record;
begin
    if not exists (
        select 1 from public.profiles p join auth.users u on u.id = p.id
        where p.id = p_actor and p.role = 'admin' and u.email_confirmed_at is not null
    ) then
        raise exception 'A verified administrator is required' using errcode = '42501';
    end if;
    if p_subject is null or char_length(btrim(p_subject)) not between 1 and 200
        or p_subject ~ '[\r\n]'
        or p_text is null or char_length(btrim(p_text)) not between 1 and 20000 then
        raise exception 'Invalid newsletter content' using errcode = '22023';
    end if;
    if p_auth_page_url is null or p_auth_page_url !~ '^https?://[^[:space:]#]+$' then
        raise exception 'A valid auth page URL is required' using errcode = '22023';
    end if;

    insert into public.mail_campaigns (subject, created_by, created_at)
    values (btrim(p_subject), p_actor, v_now) returning id into v_campaign;

    -- One query snapshot and a transaction guarantee no partially queued campaign.
    for v_rec in
        select p.id, u.email from public.profiles p join auth.users u on u.id = p.id
        where p.newsletter_opt_in and u.email_confirmed_at is not null and u.email is not null
        order by p.id limit 501
    loop
        if v_queued >= 500 then
            raise exception 'MVP newsletter limit is 500 recipients' using errcode = '22023';
        end if;
        -- Two random UUIDs supply 244 random bits; only their SHA-256 hash is stored
        -- in the token lookup. The full link necessarily remains in private outbox.
        v_token := replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', '');
        insert into public.mail_unsubscribe_tokens (token_hash, user_id, expires_at)
        values (encode(sha256(convert_to(v_token, 'UTF8')), 'hex'), v_rec.id, v_now + 31536000);
        insert into public.mail_outbox (
            campaign_id, user_id, recipient, subject, body, created_at
        ) values (
            v_campaign, v_rec.id, v_rec.email, btrim(p_subject),
            btrim(p_text) || E'\n\nВы получили письмо, потому что подписались на новости AI Sana.'
                || E'\nОтписаться: ' || p_auth_page_url || '#unsubscribe=' || v_token,
            v_now
        );
        v_queued := v_queued + 1;
    end loop;
    return jsonb_build_object('id', v_campaign, 'queued', v_queued);
end;
$$;

create or replace function public.claim_mail_job(p_now bigint)
returns setof public.mail_outbox
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_job public.mail_outbox%rowtype;
    v_current_email text;
begin
    loop
        select * into v_job from public.mail_outbox
        where status in ('pending', 'sending') and next_attempt <= p_now
        order by next_attempt, id for update skip locked limit 1;
        if not found then return; end if;

        select u.email into v_current_email
        from public.profiles p join auth.users u on u.id = p.id
        where p.id = v_job.user_id and p.newsletter_opt_in
            and u.email_confirmed_at is not null and u.email is not null;
        if not found then
            update public.mail_outbox set status = 'skipped', last_error = 'Consent or verified account is unavailable'
            where id = v_job.id;
            continue;
        end if;
        if v_job.attempts >= 5 then
            update public.mail_outbox set status = 'failed', last_error = 'Delivery retry limit reached'
            where id = v_job.id;
            continue;
        end if;

        -- Lease enables retry after a crashed worker. Attempt number fences stale
        -- workers; backend completion PATCH must filter BOTH id and attempts.
        update public.mail_outbox
        set status = 'sending', attempts = attempts + 1,
            next_attempt = p_now + 300, recipient = v_current_email, last_error = null
        where id = v_job.id returning * into v_job;
        return next v_job;
        return;
    end loop;
end;
$$;

create or replace function public.unsubscribe_mail(p_token_hash text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_user uuid;
begin
    delete from public.mail_unsubscribe_tokens
    where token_hash = p_token_hash and expires_at > extract(epoch from now())::bigint
    returning user_id into v_user;
    if v_user is null then return false; end if;
    update public.profiles set newsletter_opt_in = false where id = v_user;
    -- Invalidate all older unsubscribe links once this consent has been revoked.
    delete from public.mail_unsubscribe_tokens where user_id = v_user;
    return true;
end;
$$;

revoke all on function public.queue_newsletter(uuid, text, text, text) from public, anon, authenticated;
revoke all on function public.claim_mail_job(bigint) from public, anon, authenticated;
revoke all on function public.unsubscribe_mail(text) from public, anon, authenticated;
grant execute on function public.queue_newsletter(uuid, text, text, text) to service_role;
grant execute on function public.claim_mail_job(bigint) to service_role;
grant execute on function public.unsubscribe_mail(text) to service_role;

commit;
